@startuml
entity Users{
    * u_id: INT <<generated>>
    ---
    name_first: VARCHAR(20)
    name_last: VARCHAR(20)
    email: VARCHAR(50)
    password: VARCHAR(60)
}

entity Events{
    * e_id: INT <<generated>>
    ---
    * u_id: INT
    title: VARCHAR(30)
    e_date: DATE
    e_time: TIME
    description: VARCHAR(255)

}

    Users::u_id ||-r-|{ Events::u_id
@enduml